# fly.toml app configuration file for opnform-api
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'opnform-api'
primary_region = 'dfw'
release_command = "php artisan migrate --force"

[build]
  image = 'jhumanj/opnform-api:1.9.3'

[env]
  APP_DEBUG = 'false'
  APP_ENV = 'production'
  APP_NAME = 'OpnForm'
  APP_URL = 'https://your-nuxthub-app-url.com' # <-- Important: Update this to your NuxtHub frontend URL
  TRUSTED_PROXIES = '*'
  CACHE_DRIVER = 'redis'
  DB_CONNECTION = 'pgsql'
  FILESYSTEM_DRIVER = 's3'
  AWS_USE_PATH_STYLE_ENDPOINT = 'true'
  JWT_SKIP_IP_UA_VALIDATION = 'true'
  LOCAL_FILESYSTEM_VISIBILITY = 'public'
  LOG_CHANNEL = 'errorlog'
  LOG_LEVEL = 'debug'
  PHP_MAX_EXECUTION_TIME = '600'
  PHP_MEMORY_LIMIT = '1G'
  PHP_POST_MAX_SIZE = '64M'
  PHP_UPLOAD_MAX_FILESIZE = '64M'
  QUEUE_CONNECTION = 'redis'
  REDIS_HOST = 'opnform-redis.internal' # Added for Fly.io Redis
  SELF_HOSTED = 'true'
  SESSION_DRIVER = 'redis'
  SESSION_LIFETIME = '120'
  SHOW_OFFICIAL_TEMPLATES = 'true'

[processes]
  app = "sh -lc \"php-fpm & php artisan schedule:work & php artisan queue:work\""

[services]
  protocol = "tcp"
  internal_port = 9000
  auto_stop_machines = "suspend"
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

  [[services.ports]]
    port = 9000

  [checks]
    [checks.api]
      port = 9000
      type = "tcp"
      interval = "15s"
      timeout = "2s"
      grace_period = "5s"

[[vm]]
  memory = '512mb'
  cpu_kind = 'shared'
  cpus = 1
