# .github/workflows/production.yml

name: Deploy Production (Bref)

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy to Production
    runs-on: ubuntu-latest
    # These permissions are needed for the Serverless Framework to communicate with AWS.
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, bcmath, soap, intl, gd, exif
          coverage: none

      - name: Install Composer Dependencies
        run: composer install --prefer-dist --no-progress --no-dev
        working-directory: ./api

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          # This uses OpenID Connect to securely authenticate with AWS.
          # You must configure this in your AWS account.
          role-to-assume: ${{ secrets.AWS_IAM_ROLE_PROD }}
          aws-region: us-east-1 # Change to your desired region

      - name: Deploy to AWS with Serverless Framework
        run: npx serverless deploy --stage prod
        working-directory: ./api
        env:
          # Pass any required secrets or environment variables here
          # It's recommended to use AWS SSM Parameter Store for secrets
          # For example: APP_KEY: ${{ secrets.APP_KEY_PROD }}
          # DB_PASSWORD: ${{ secrets.DB_PASSWORD_PROD }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}